/**
 * Inbound prompt template: project profile.
 * Injected into the agent's system prompt on every `ci run <agent>` call.
 * See PLAN.md §17.3 for the full specification.
 */

export interface ProjectProfilePromptData {
  folders: string[];
  adrs: string[];
  namingRegex: string;
  dependencies: string[];
  lintConfig: string;
}

export function renderProjectProfilePrompt(data: ProjectProfilePromptData): string {
  return `
# Project Profile (auto-generated by Continuous Improvement)

You are operating inside a project that has been scanned by \`ci scan\`.
The following facts are durable knowledge about this repo. Treat them as
**ground truth** for this session.

## Folder layout
${data.folders.map((f) => `- \`${f}\``).join("\n")}

## Architecture Decision Records (ADRs)
${data.adrs.length === 0 ? "_No ADRs found._" : data.adrs.map((a) => `- ${a}`).join("\n")}

## Naming conventions
\`${data.namingRegex}\`

## Allowed dependencies
${data.dependencies.map((d) => `- \`${d}\``).join("\n")}

## Lint config
\`\`\`
${data.lintConfig}
\`\`\`

## Hard constraints
- **Do not** introduce a dependency that is not in \`allowed dependencies\`.
- **Do not** violate any ADR above.
- **Do not** break the naming conventions above without first updating
  them via \`ci scan --update\`.

If the user asks you to do something that contradicts this profile, ASK
THE USER before proceeding. Do not silently override.
`.trim();
}

/** Default placeholder (used when no profile has been generated yet). */
export const PROJECT_PROFILE_PROMPT = renderProjectProfilePrompt({
  folders: ["src/", "tests/", "docs/"],
  adrs: [],
  namingRegex: "kebab-case for files, camelCase for variables",
  dependencies: [],
  lintConfig: "(no lint config detected)",
});
