/**
 * Inbound prompt template: active rules.
 * Injected into the agent's system prompt on every `ci run <agent>` call.
 * See PLAN.md §17.4 for the full specification.
 */

export interface RulePromptData {
  id: string;
  action: "block" | "warn" | "suggest";
  priority: number;
  condition: string;
  do_: string;
}

export function renderRulesPrompt(rules: RulePromptData[]): string {
  const ruleBlocks = rules
    .map(
      (r) => `
## Rule ${r.id} — ${r.action} (priority ${r.priority})
**When:** ${r.condition}
**Do:** ${r.do_}
`.trim(),
    )
    .join("\n\n");

  return `
# Active Rules (auto-generated by Continuous Improvement)

The following rules were learned from past mistakes in this repo. You
MUST obey **hard** (\`block\`) rules. For **soft** (\`warn\` or \`suggest\`)
rules, prefer the rule's suggestion but you may ask the user for
confirmation.

${
  rules.length === 0
    ? "_No active rules yet._"
    : ruleBlocks
}

## When a rule conflicts with the user's request
1. Hard rule (\`block\`): refuse, explain which rule, ask the user to
   either \`ci rules rm <id>\` or override explicitly.
2. Soft rule (\`warn\` or \`suggest\`): do the safer thing, then ask
   the user after the fact.
3. If the user says "ignore rule X for this turn", do so and log an
   event via the adapter's \`emit_event\` (event_type = RULE_OVERRIDDEN).
`.trim();
}

/** Default empty rules prompt. */
export const RULES_PROMPT = renderRulesPrompt([]);
